baseUrl: "https://jonathanhunsucker.com/"
title: "Jonathan Hunsucker"
staticDir: "static/"
assetDir: "assets/"
googleAnalytics: ""
menu:
  main:
    - identifier: home
      name: Posts
      url: /
    - identifier: projects
      name: Projects
      url: /projects
