---
label: Post
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: publishDate
  label: publishDate
pages:
- content/posts/visualizing-covid-19-new-cases-daily.md
